language: bash
sudo: required
services:
- docker
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq
    && cd $(pwd) && snapcraft && snapcraft push *.snap --release edge"
  skip_cleanup: true
